nasdaqengine/nasdaqengine/urls.py
from django.contrib import admin
from django.urls import path, include
from nasdaqstat.views import TickerList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TickerList.as_view(), name='web_ticker_list_url'),
    path('api/', TickerList.as_view(), {'api': True}, name='ticker_list_url'),
    path('<str:ticker>/', include(('nasdaqstat.urls', 'nasdaqstat'), namespace='web')),
    path('api/<str:ticker>/', include(('nasdaqstat.urls', 'nasdaqstat'), namespace='api'), {'api': True}),
]

nasdaqengine/nasdaqstat/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', TickerHistorical.as_view(), name='ticker_historical_url'),
    path('insider/', TickerInsiderTrades.as_view(), name='ticker_insider_trades_url'),
    path('insider/<str:insider_name>/', InsiderOperations.as_view(), name='insider_operations_url'),
    path('analytics', Analytics.as_view(), name='analytics_url'),
    path('delta', Delta.as_view(), name='delta_url'),
]

nasdaqengine/nasdaqstat/models.py
from django.db import models


class Historical(models.Model):
    ticker = models.ForeignKey('Company', null=True, blank=True, on_delete=models.CASCADE)
    date = models.DateField()
    open = models.FloatField()
    high = models.FloatField()
    low = models.FloatField()
    close = models.FloatField()
    volume = models.FloatField()

    def __str__(self):
        return 'volume={}'.format(str(self.volume))


class Company(models.Model):
    ticker = models.CharField(max_length=40)

    def __str__(self):
        return self.ticker


class Insider(models.Model):
    name = models.CharField(max_length=40)
    relation = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class InsiderTrades(models.Model):
    ticker = models.ForeignKey('Company', null=True, blank=True, on_delete=models.CASCADE)
    insider = models.ForeignKey('Insider', null=True, blank=True, on_delete=models.CASCADE)
    last_date = models.DateField()
    transaction_type = models.CharField(max_length=60)
    owner_type = models.CharField(max_length=40)
    shares_traded = models.FloatField()
    last_price = models.FloatField(null=True, blank=True)
    shares_held = models.FloatField()

    def __str__(self):
        return '{} - {} - {}'.format(self.ticker, self.insider, self.last_date)

nasdaqengine/nasdaqstat/views.py
import json

from django.core import serializers
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.db import connection

from .models import *

from django.core.paginator import Paginator


class TickerList(View):
    def get(self, request, api=False):
        tickers = Company.objects.all()

        if api:
            context_api = serializers.serialize('json', tickers, indent=4)
            return HttpResponse(context_api, content_type='application/json')

        return render(request, 'nasdaqstat/index.html', context={'tickers': tickers})


class TickerHistorical(View):
    def get(self, request, ticker, api=False):
        ticker_obj = get_object_or_404(Company, ticker__iexact=ticker)
        ticker_historical = Historical.objects.filter(ticker=ticker_obj)

        context = {'ticker': ticker,
                   'ticker_historical': ticker_historical,
                   }

        if api:
            context_api = serializers.serialize('json', ticker_historical, indent=4)
            return HttpResponse(context_api, content_type='application/json')

        return render(request, 'nasdaqstat/historical.html', context=context)


class TickerInsiderTrades(View):
    def get(self, request, ticker, api=False):
        ticker_obj = Company.objects.get(ticker=ticker)
        ticker_insider_trades = InsiderTrades.objects.filter(ticker=ticker_obj)

        rows_per_page = 15

        paginator = Paginator(ticker_insider_trades, rows_per_page)
        page_number = request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        is_paginated = page.has_other_pages()

        if page.has_previous():
            prev_url = '?page={}'.format(page.previous_page_number())
        else:
            prev_url = ''

        if page.has_next():
            next_url = '?page={}'.format(page.next_page_number())
        else:
            next_url = ''

        context = {'ticker': ticker,
                   'ticker_insider_trades': ticker_insider_trades,
                   'page_object': page,
                   'is_paginated': is_paginated,
                   'next_url': next_url,
                   'prev_url': prev_url,
                   }

        if api:
            context_api = serializers.serialize('json', ticker_insider_trades, indent=4)
            return HttpResponse(context_api, content_type='application/json')

        return render(request, 'nasdaqstat/insider_trades.html', context=context)


class InsiderOperations(View):
    def get(self, request, ticker, insider_name, api=False):
        ticker_obj = Company.objects.get(ticker=ticker)
        insider_obj = Insider.objects.get(name=insider_name)
        insider_operations = InsiderTrades.objects.filter(ticker=ticker_obj).filter(insider=insider_obj.id)

        context = {'ticker': ticker,
                   'insider_operations': insider_operations,
                   'insider_name': insider_name,
                   }

        if api:
            context_api = serializers.serialize('json', insider_operations, indent=4)
            return HttpResponse(context_api, content_type='application/json')

        return render(request, 'nasdaqstat/insider_operations.html', context)


class Analytics(View):
    def get(self, request, ticker, api=False):
        analytics_query = request.GET

        if analytics_query['date_from'] and analytics_query['date_to']:
            ticker_obj = Company.objects.get(ticker=ticker)
            date_from_obj = Historical.objects.filter(ticker=ticker_obj).get(date=analytics_query['date_from'])
            date_to_obj = Historical.objects.filter(ticker=ticker_obj).get(date=analytics_query['date_to'])
            difference = dict(open=round(date_to_obj.open - date_from_obj.open, 3),
                              high=round(date_to_obj.high - date_from_obj.high, 3),
                              low=round(date_to_obj.low - date_from_obj.low, 3),
                              close=round(date_to_obj.close - date_from_obj.close, 3))

            context = {'ticker': ticker,
                       'date_from': date_from_obj,
                       'date_to': date_to_obj,
                       'difference': difference,
                       }

            if api:
                dump = json.dumps(difference, indent=4)
                return HttpResponse(dump, content_type='application/json')

            return render(request, 'nasdaqstat/analytics.html', context)


class Delta(View):
    def get(self, request, ticker, api=False):
        ticker_obj = Company.objects.get(ticker=ticker).id
        delta_query = request.GET

        if int(delta_query['value']) and delta_query['type'] in ['open', 'high', 'low', 'close']:
            query = (" SELECT MAX( select1.date ), date2 {up} FROM ("
                     " SELECT t1.date, t1.{type}, "
                     " MIN(t2.date) as date2 "
                     " FROM nasdaqstat_historical t1 "
                     " INNER JOIN nasdaqstat_historical t2 "
                     " ON (t2.{type} >= t1.{type} + {value} ) "
                     " AND t1.date < t2.date "
                     " AND t1.ticker_id = t2.ticker_id "
                     " WHERE t1.ticker_id = {ticker_id} "
                     " GROUP BY t1.id "
                     " ORDER BY t1.date ) select1 "
                     " GROUP BY date2 "
                     " UNION "
                     " SELECT MAX( select2.date ), date2{down} FROM ( "
                     " SELECT t1.date, t1.{type}, "
                     " MIN(t2.date) as date2 "
                     " FROM nasdaqstat_historical t1 "
                     " INNER JOIN nasdaqstat_historical t2 "
                     " ON (t2.{type} <= t1.{type} - {value} ) "
                     " AND t1.date < t2.date "
                     " AND t1.ticker_id = t2.ticker_id "
                     " WHERE t1.ticker_id = {ticker_id} "
                     " GROUP BY t1.id "
                     " ORDER BY t1.date ) select2 "
                     " GROUP BY date2 "
                     " ORDER BY date2; ".format(ticker_id=ticker_obj,
                                                value=delta_query['value'],
                                                type=delta_query['type'],
                                                up=", 'UP' direction",
                                                down=", 'DOWN' as direction")
                     )

            cursor = connection.cursor()
            cursor.execute(query)
            row = cursor.fetchall()

            context = {'ticker': ticker, 'row': row, 'type': delta_query['type'], 'value': delta_query['value']}

            if api:
                times = []
                for record in row:
                    start, finish = record[0], record[1]
                    answer = {'start': start.strftime('%m/%d/%Y'), 'finish': finish.strftime('%m/%d/%Y'),
                              'status': record[2]}
                    times.append(answer)

                return HttpResponse(json.dumps(times), content_type='application/json')

            return render(request, 'nasdaqstat/delta.html', context)

nasdaqengine/nasdaqstat/templates/nasdaqstat/analytics.html
{% extends 'nasdaqstat/base_nasdaqstat.html' %}
{% block title %}
  Analytics for {{ ticker }} - {{ block.super }}
{% endblock%}
{% block content %}

  <div class="row">
    <div class="col-7 ml-3">
      <div class="d-flex justify-content-between">

        <div class="p-2" style="margin-left: -200px;">
          <div>
            <h2>Difference for prices of {{ ticker }}</h2>
          </div>
        </div>

      </div>
      <div style="margin-left: -200px;">
        <table class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col">Date</th>
              <th scope="col">Open</th>
              <th scope="col">High</th>
              <th scope="col">Low</th>
              <th scope="col">Close / Last</th>
            </tr>
          </thead>
          <tbody>
              <tr>
                <td>{{ date_from.date }}</td>
                <td>{{ date_from.open }}</td>
                <td>{{ date_from.high }}</td>
                <td>{{ date_from.low }}</td>
                <td>{{ date_from.close }}</td>
              </tr>
              <tr>
                <td>{{ date_to.date }}</td>
                <td>{{ date_to.open }}</td>
                <td>{{ date_to.high }}</td>
                <td>{{ date_to.low }}</td>
                <td>{{ date_to.close }}</td>
              </tr>
              <tr>
                <td>Difference</td>
                <td>{{ difference.open }}</td>
                <td>{{ difference.high }}</td>
                <td>{{ difference.low }}</td>
                <td>{{ difference.close }}</td>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

nasdaqengine/nasdaqstat/templates/nasdaqstat/base_nasdaqstat.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>

    {% block title %}
      Nasdaq Engine
    {% endblock%}

    </title>
  </head>
  <body>

  <!-- Navigation panel -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="{% url 'web_ticker_list_url' %}">
        Nasdaq Statistics
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">

      </div>
    </nav>

    <!-- Container -->
    <div class="container mt-5 mb-4">
      <div class="row mb-4">
        <div class="col-12 offset-md-5 mt-5 mb-4">
          {% block content %}
            Some content
          {% endblock %}
        </div>
      </div>
    </div>
    <footer class="footer fixed-bottom py-3 bg-light">
      <div class="container">
        <p class="m-0 text-center text-muted">NASDAQ STATISTICS</p>
      </div>
    </footer>
  </body>
</html>

nasdaqengine/nasdaqstat/templates/nasdaqstat/delta.html
{% extends 'nasdaqstat/base_nasdaqstat.html' %}
{% block title %}
  Delta for {{ ticker }} - {{ block.super }}
{% endblock%}
{% block content %}

  <div class="row">
    <div class="col-7 ml-3">
      <div class="d-flex justify-content-between">

        <div class="p-2" style="margin-left: -200px;">
          <div>
            <h2>Delta for {{ ticker }}</h2>
          </div>
        </div>

      </div>
      <div style="margin-left: -200px;">
        <table class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col">Price Difference</th>
              <th scope="col">Start date</th>
              <th scope="col">End date</th>
            </tr>
          </thead>
          <tbody>

          {% for date in row %}

              {% if date.2 == 'UP' %}
                  <tr>
                    <td>Growth</td>
              {% else %}
                  <tr>
                    <td>Down</td>
              {% endif %}
                    <td>{{ date.0 }}</td>
                    <td>{{ date.1 }}</td>
                  </tr>

          {% endfor %}

          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

nasdaqengine/nasdaqstat/templates/nasdaqstat/historical.html
{% extends 'nasdaqstat/base_nasdaqstat.html' %}
{% block title %}
  Historical {{ ticker }} - {{ block.super }}
{% endblock%}
{% block content %}

  <div class="row">
    <div class="col-5 ml-3">
      <div class="d-flex">

        <div class="p-2" style="margin-left: -200px;">
          <div>
            <h2>{{ ticker }}</h2>
          </div>
        </div>

        <div class="p-2" style="margin-right: 500px;">
            <a class="btn btn-primary" href="{% url 'web:ticker_insider_trades_url' ticker %}" role="button">Insiders</a>
        </div>

      </div>
      <div style="margin-left: -200px;">
        <table class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col">Date</th>
              <th scope="col">Open</th>
              <th scope="col">High</th>
              <th scope="col">Low</th>
              <th scope="col">Close / Last</th>
              <th scope="col">Volume</th>
            </tr>
          </thead>
          <tbody>
            {% for row in ticker_historical %}
              <tr>
                <td>{{ row.date }}</td>
                <td>{{ row.open }}</td>
                <td>{{ row.high }}</td>
                <td>{{ row.low }}</td>
                <td>{{ row.close }}</td>
                <td>{{ row.volume }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

nasdaqengine/nasdaqstat/templates/nasdaqstat/index.html
{% extends 'nasdaqstat/base_nasdaqstat.html' %}
{% block title %}
  Nasdaq Engine
{% endblock%}
{% block content %}
  <div style="margin-left: 15px;">
    <h2>All Stock</h2>
  </div>
  <div class="row">
    <div class="col-2">
      <div class="list-group">
        {% for ticker in tickers %}
          <a href="{{ ticker }}" class="list-group-item list-group-item-action">
            {{ ticker }}
          </a>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

nasdaqengine/nasdaqstat/templates/nasdaqstat/insider_operations.html
{% extends 'nasdaqstat/base_nasdaqstat.html' %}
{% block title %}
  Insider Trades of {{ insider_name }} - {{ block.super }}
{% endblock%}
{% block content %}

  <div class="row">
    <div class="col-7 ml-3">
      <div class="d-flex justify-content-between">

        <div class="p-2" style="margin-left: -200px;">
          <div>
            <h2>Insider Trades of {{ insider_name }}</h2>
          </div>
        </div>

      </div>
      <div style="margin-left: -200px;">
        <table class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col">Company</th>
              <th scope="col">Relation</th>
              <th scope="col">Last Date</th>
              <th scope="col">Tran</th>
              <th scope="col">Owner Type</th>
              <th scope="col">Shares Traded</th>
              <th scope="col">Last Price</th>
              <th scope="col">Shares Held</th>
            </tr>
          </thead>
          <tbody>
            {% for row in insider_operations %}
              <tr>
                <td>{{ row.ticker }}</td>
                <td>{{ row.insider.relation }}</td>
                <td>{{ row.last_date }}</td>
                <td>{{ row.transaction_type }}</td>
                <td>{{ row.owner_type }}</td>
                <td>{{ row.shares_traded }}</td>
                <td>{{ row.last_price }}</td>
                <td>{{ row.shares_held }}</td>

              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

nasdaqengine/nasdaqstat/templates/nasdaqstat/insider_trades.html
{% extends 'nasdaqstat/base_nasdaqstat.html' %}
{% block title %}
  Insider Trades {{ ticker }} - {{ block.super }}
{% endblock%}
{% block content %}
  <div class="row">
    <div class="col-7 ml-3">
      <div class="d-flex justify-content-between">
        <div class="p-2" style="margin-left: -200px;">
          <div>
            <h2>{{ ticker }}</h2>
          </div>
        </div>
      </div>
      <div style="margin-left: -200px;">
        <table class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col">Insider</th>
              <th scope="col">Relation</th>
              <th scope="col">Last Date</th>
              <th scope="col">Transaction Type</th>
              <th scope="col">Owner Type</th>
              <th scope="col">Shares Traded</th>
              <th scope="col">Last Price</th>
              <th scope="col">Shares Held</th>
            </tr>
          </thead>
          <tbody>
            {% for row in page_object.object_list %}
              <tr>
                <td><a href="/{{ ticker }}/insider/{{ row.insider }}">{{ row.insider }}</a></td>
                <td>{{ row.insider.relation }}</td>
                <td>{{ row.last_date }}</td>
                <td>{{ row.transaction_type }}</td>
                <td>{{ row.owner_type }}</td>
                <td>{{ row.shares_traded }}</td>
                <td>{{ row.last_price }}</td>
                <td>{{ row.shares_held }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <!-- Pagination -->

  {% if is_paginated %}
    <nav aria-label="..." >
      <ul class="pagination">
        <li class="page-item {% if not prev_url %} disabled {% endif %}">
        <a class="page-link" href="{{ prev_url }}" tabindex="-1" aria-disabled="true">Previous</a>
      </li>
      {% for n in page_object.paginator.page_range %}
        {% if page_object.number == n %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ n }}">{{ n }} <span class="sr-only">(current)</span></a>
          </li>
          {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
          <li class="page-item">
            <a class="page-link" href="?page={{ n }}">{{ n }}</a>
          </li>
        {% endif %}
      {% endfor %}
      <li class="page-item {% if not next_url %} disabled {% endif %}">
      <a class="page-link" href="{{ next_url }}" tabindex="-1" aria-disabled="true">Next</a>
    </li>
  </ul>
</nav>
{% endif %}
{% endblock %}